<a href="https://colab.research.google.com/github/njaincode/python_for_data_science/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Using numpy for processing arrays and matrices of number data

---

## numpy is a more efficient array processing library for Python

Python lists can contain any type of data, including objects.  numpy arrays are specialised and can only contain numbers.

You can customise the memory usage so that arrays can use less memory and items are stored contiguously.  This means that it is more efficient/faster processing large data sets.

Use numpy arrays to store and manipulate large lists of numbers (for other data types use plain Python lists or a panda series)


---
### Creating a numpy array from a Python list

To use numpy, you will need to import it.  The conventional way to import numpy is to import the whole library and use an *alias*

`import numpy as np`

Every time you want to use a function from the numpy library you use the syntax:  
`np.function_name()`  

Create a new numpy array from a Python list of numbers
   
`arr = np.array([1,2,3])`

Or a new numpy matrix from a Python 2 dimensional list of numbers

`matrix = np.array([1,2,3],[4,5,6])`

---
### Exercise 1 - create a numpy array from a given list

Write a function called `make_array(num_list`) which will:
*   accept num_list as a parameter  
*   create a new numpy array called **new_array** from `num_list`
*   print `new_array`

Test input:  
[3,6,2,5,8,6]  

Expected output:  
[3,6,2,5,8,6]  



In [2]:
import numpy as np

def make_array(num_list):
  new_array = np.array(num_list)
  print(new_array)

  # Change value in num_list and it should not change np array?
  num_list[0] = 1
  # num_list elements are ',' separated whereas, np doesn't
  print(num_list, new_array)

make_array([3,6,2,5,8,6])


[3 6 2 5 8 6]
[1, 6, 2, 5, 8, 6] [3 6 2 5 8 6]


## Setting the number type in memory

numpy allows you to set the type of number in memory (e.g. int8, int32) when you create the array.  This allows memory allocation to be as small as possible.  

`new_matrix = np.array([[1, 2, 3], [4, 5, 6]], np.int8)`    

This creates a two row, three column matrix of whole numbers which are all small enough to fit in 1 byte of memory storage.

---
### Exercise 2 - create matrix of smallish numbers

Write a function which will:
*   accept a parameter **num_list** which will be a 2-dimensional list  
*   create a new numpy array called **new_matrix** from `num_list`, with data size `int16`
*   print `new_matrix` one list per line

Test input:  
[31112, 32321, 24567],[456,324,789]

Expected output:   
[31112, 32321, 24567]  
[456,324,789]  
 


In [21]:
import numpy as np

def create_matrix(num_list):
  new_matrix = np.array(num_list, np.int16)
  print(new_matrix.ndim)
  print(new_matrix)


list1 = [[31112, 32321, 24567], [456, 324, 789]]

print(list1)

create_matrix(list1)


[[31112, 32321, 24567], [456, 324, 789]]
2
[[31112 32321 24567]
 [  456   324   789]]


---
### Exercise 3 - make a 3 x 3 numpy array

Write a function which  will create a 3 x 3 array, then print the array one row per line.

Test data:  
[[1,2,3],[4,5,6],[7,8,9]]

Expected output:  
[1 2 3]  
[4 5 6]  
[7 8 9]  

In [4]:
import numpy as np

def create_3d_array():
  # Note its dimensions show up as (3,1,3)
  n3d_array = np.array([[[1,2,3]],[[4,5,6]],[[7,8,9]]], np.int8)
  print(n3d_array.ndim, n3d_array.shape)
  print(n3d_array)

def gen_3d_arr():
  a = np.array([(1,2,3),(4,5,6),(7,8,9)])
  print(f'a \n {a}')
  print(a.size)
  print(a.shape)

  b = np.array([[1,2,3],[4,5,6],[7,8,9]])
  print(f'b \n {b}')
  print(b.size)
  print(b.shape)

  c = np.arange(1,10,1)
  c = c.reshape(3,3)
  print(f'c \n {c}')
  print(c.size)
  print(c.shape)




create_3d_array()
gen_3d_arr()

3 (3, 1, 3)
[[[1 2 3]]

 [[4 5 6]]

 [[7 8 9]]]
a 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
9
(3, 3)
b 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
9
(3, 3)
c 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
9
(3, 3)


---
### Exercise 4 - make a 2 x 2 x 2 numpy array

Write a function which will create a 2 x 2 x 2 array, then print the array one individual array per line.

Test data:
[[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]]

Expected output:
[1,2]  
[3,4]  
[5,6]  
[7,8]  
[9,10]  
[11,12]  

In [14]:
import numpy as np

def create_4d_array():
  n4d_array = np.array([[[1,2],[3,4]], [[5,6],[7,8]], [[9,10],[11,12]]], np.int8)
  print(n4d_array.ndim, n4d_array.shape)
  print(n4d_array)
  print(f'One element\n {n4d_array[0]}, dim {n4d_array[0].ndim} ')
  print(f'One-one element\n {n4d_array[0][0]}, dim {n4d_array[0][0].ndim} ')


# This function is written after watching youtube videos
def gen_4d_arr():
  # e is only for experiment
  e = np.zeros((2,2,2), np.int8)
  print(f'e \n {e}')
  print(e.size)
  print(e.shape)

  b = np.arange(1,9,1)
  b = b.reshape(2,2,2) 
  print(f'b \n {b}')
  print(b.size)
  print(b.shape)

  a = np.arange(1,13,1)
  a = a.reshape(6,2) # FIXME shape (2,2,2) is not possible with 12 elements
  print(f'a \n {a}')
  print(a.size)
  print(a.shape)




#create_4d_array()
gen_4d_arr()

e 
 [[[0 0]
  [0 0]]

 [[0 0]
  [0 0]]]
8
(2, 2, 2)
b 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
8
(2, 2, 2)
a 
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
12
(6, 2)


## Inspecting the shape of the array/matrix

numpy provides the `np.shape` property for reporting the shape of a numpy array.  np.shape will give the number of layers, rows, columns (and more if necessary) present in the array.  Arrays can be multi-dimensional but we will only arrays of maximum 3 dimensions to keep it simple.  

Example:  
```
matrix = np.array([[[1,1],[2,2],[3,3]],[[4,4],[5,5],[6,6]]])
print(matrix.shape)
```

Expected output:  
(2, 3, 2)

This matrix has 2 layers of 3 rows of 2 columns

---
### Exercise 5 - print the shape

Write a function which will:  
*  create a numpy array using the test data below
*  print the shape of the array

Test 1 data:  
[3,7,56]

Expected output:
(3,)

Test 2 data:  
[[7,6,5,8,4,9],[3,7,5,8,6,9]]

Expected output:  
(2,6)

In [15]:
import numpy as np

# shape is not a function, it is a variable
def print_arr_shape():
  a = np.array([3,7,56], np.int8)
  print(f'a\n {a.shape}')

  b = np.array([[7,6,5,8,4,9],[3,7,5,8,6,9]], np.int8)
  print(f'b\n {b.shape}')

print_arr_shape()


a
 (3,)
b
 (2, 6)


---
### Exercise 6 - using slicing to print parts of arrays

Write a function which will:  
*  create an array from the Python list [1,2,3,4,5]
*  print the first 3 items in the array
*  print the last item in the array

In [17]:
import numpy as np

def arr_slice():
  a = np.arange(1,6,1)
  print(f'a\n {a.shape} \n {a}')
  # Print first 3 items in array
  print(f'First 3 items = {a[:3]}')
  print(f'Last item = {a[-1]}')

arr_slice()


a
 (5,) 
 [1 2 3 4 5]
First 3 items = [1 2 3]
Last item = 5


---
### Exercise 7 - using slicing to print parts of array rows and columns

Write a function which will:  
*  create an array from the Python 2 dimsensional list [[1,2,3,4],[5,6,7,8],[9,1,2,3]]
*  print the first item in the second row   
*  print the first 2 rows only
*  print the last 2 items in the last 2 rows

Expected output:  
5  
[[1,2,3,4],[5,6,7,8]]  
[[7,8],[2,3]]

In [38]:
import numpy as np

def arr_row_col():
  a = np.array([[1,2,3,4],[5,6,7,8],[9,1,2,3]])
  #a = a.reshape(3,4) # make 3x4 matrix
  print(f'a\n {a.shape} \n {a}')
  
  print(f'First item in 2nd row = {a[1][0]}')
  # How to print multiple rows? Index 2 is not inclusive
  # If [0:1] is used, 1 is not included only 0 will be printed
  print(f'First two rows \n= {a[:2]}')
  # [dim0, dim1]
  print(f'Last 2 items in last two rows\n = {a[-2:, -2:]}')

arr_row_col()


a
 (3, 4) 
 [[1 2 3 4]
 [5 6 7 8]
 [9 1 2 3]]
First item in 2nd row = 5
First two rows 
= [[1 2 3 4]
 [5 6 7 8]]
Last 2 items in last two rows
 = [[7 8]
 [2 3]]


---
## Broadcasting an operation across an array

Because a numpy array is created from a related set of data, it is useful to be able to operate on every item in the array in the same way.  For instance, the array might hold a set of scores out of 30 and you might want to convert all scores into percentages.

We can do this in a number of ways:  
1.  Create a new array to store the result after the operation in the new array
```
scores = np.array([29,25,15,22,30])
percentages = scores / 30 * 100
print(percentages)
```
Expected output:  [ 96.66666667  83.33333333  50.  73.33333333 100. ]  

2.  Store the result in the original array
```
scores = np.array([29,25,15,22,30])
scores = scores / 30 * 100
print(scores)
```
Expected output:  [ 96.66666667  83.33333333  50.  73.33333333 100. ]

Give it a try:





---
### Exercise 8 - increase whole array by 20

Write a function which will:
*  create a numpy array of 12 numbers
*  create a new array adding 20 to each of the items in the first array  
*  print the new array

Test input:  
[1,2,3,4,5,6,7,8,1,2,3,4]  

Expected output:  
[21,22,23,24,25,26,27,28,21,22,23,24]

In [42]:
import numpy as np

def arr_op():
  a = np.random.randint(0,100,12,dtype=np.int8)
  print(a)
  a += 20
  print(f'After adding 20 a \n {a}')

arr_op()

[83 99 47  3 44  5 38 50 44 58 12 72]
After adding 20 a 
 [103 119  67  23  64  25  58  70  64  78  32  92]


---
## Using functions to create arrays of 1s, 0s or a range of numbers

You can use np.arange(range) to create an array with a range of numbers.  Like range in Python, either give 1 number to get all numbers from 0 to the number before it, or give 2 numbers to get the numbers from the first to one before the last.  You can specify the start number, the stop number and a step size (e.g. (1,9,2) will generate [1 3 5 7]:
```
array1 = np.arange(10)
```
will give array1 = [0,1,2,3,4,5,6,7,8,9]

```
array2 = np.arange(2,9)
```
will give array2 = [2,3,4,5,6,7,8]

```
array3 = np.arange(2,9,3)
```
will give array3 = [2,5,8]  

---

To create a new array of 10 zeros:
```
array4 = np.zeros(10)
```
will give array4 = [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

To create a new array of 10 zeros as integers:
```
array5 = np.zeros(10, dtype='int32')
```
will give array5 = [0 0 0 0 0 0 0 0 0 0]

To create a new array of 8 ones:  
```
array6 = np.ones(8, dtype='int16')
```
will give array6 = [1 1 1 1 1 1 1 1]

---
### Exercise 9 - create a numpy array of the numbers 1 to 8  

Write a function which will:  
*  create a numpy array with the numbers 1 to 8 using np.arange()  
*  create a second numpy array with 12 zeros
*  create a third numpy array with 4 ones
*  create a fourth numpy array with the the multiples of 10 from 10 to 100 (use arange with start, stop and step)

Expected output:  
[1 2 3 4 5 6 7 8]  
[0 0 0 0 0 0 0 0 0 0 0 0]  
[1 1 1 1]  
[ 10  20  30  40  50  60  70  80  90 100]


 

In [47]:
import numpy as np

def arr_arange():
  a = np.arange(1,9)
  print(f'random array=\n {a}')

  b = np.zeros(12, dtype=np.int8)
  print(f'All 0=\n {b}')

  c = np.ones(4, dtype=np.int8)
  print(f'All 1=\n {c}')

  d = np.arange(10,101,10, dtype=np.int8)
  print(f'Multiple of 10=\n {d}')

arr_arange()

random array=
 [1 2 3 4 5 6 7 8]
All 0=
 [0 0 0 0 0 0 0 0 0 0 0 0]
All 1=
 [1 1 1 1]
Multiple of 10=
 [ 10  20  30  40  50  60  70  80  90 100]


---
### Exercise 10 - create a numpy mask matrix

**Challenging**

Write a function which will create and print a numpy array as follows:

*  create **array1** with shape=(8,8) containing all zeros of dtype int16
*  change the value of the middle two items of the middle two rows of `array1`, each to 1 (use list indexing for this)
*  print `array1`
*  change the value of the corner items to 1
*  print `array1`

Expected output:  
[[0 0 0 0 0 0 0 0]  
 [0 0 0 0 0 0 0 0]  
 [0 0 0 0 0 0 0 0]  
 [0 0 0 1 1 0 0 0]  
 [0 0 0 1 1 0 0 0]  
 [0 0 0 0 0 0 0 0]  
 [0 0 0 0 0 0 0 0]  
 [0 0 0 0 0 0 0 0]]    

 [[1 0 0 0 0 0 0 1]  
 [0 0 0 0 0 0 0 0]  
 [0 0 0 0 0 0 0 0]  
 [0 0 0 1 1 0 0 0]  
 [0 0 0 1 1 0 0 0]  
 [0 0 0 0 0 0 0 0]  
 [0 0 0 0 0 0 0 0]  
 [1 0 0 0 0 0 0 1]]  



In [6]:
import numpy as np

def create_numpy_matrix():
  array1 = np.zeros([8,8], dtype=np.int16)
  print(array1.shape, array1.size)
  # Change value of middle two items of middle two rows to 1
  array1[3:5, 3:5] = 1
  print(array1)
  # Change the value of corner items to 1
  # FIXME Can this be done in single line?
  array1[0,0] = 1
  array1[0,7] = 1
  array1[7,0] = 1
  array1[7,7] = 1
  print(array1)

  # Itemsize - size of an element ie int16 in this case 2bytes
  print(f'Itemsize={array1.itemsize}')

  # Returns positions of elements with non-zero value
  print(f'Non-zero elements {array1.nonzero()}')

create_numpy_matrix()

(8, 8) 64
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 1 1 0 0 0]
 [0 0 0 1 1 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
[[1 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 1 1 0 0 0]
 [0 0 0 1 1 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 1]]
Itemsize=2
Non-zero elements (array([0, 0, 3, 3, 4, 4, 7, 7]), array([0, 7, 3, 4, 3, 4, 0, 7]))
